### PR TITLE
dynamic_kick: fix crashes due to invalid tf transformations

### LINKED ISSUE #40: dynamic kick crashes when goals frame does not exist

### PR DESCRIPTION
**Pull request by ftsell**
this might not fix all crashes but the most obvious ones are now caught.

closes #40

### CODE REVIEW

File: bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_engine.h [hunk 1]
```diff
@@ -180,6 +185,8 @@ class KickEngine : public bitbots_splines::AbstractEngine<KickGoals, KickPositio
    * @param ball_position Position of the ball
    * @param kick_direction Direction in which to kick the ball
    * @return pair of (transformed_pose, transformed_direction)
+   *
+   * @throws tf2::TransformException when goal cannot be transformed into support_foot_frame
    */
   std::optional<std::pair<geometry_msgs::Point, geometry_msgs::Quaternion>> transformGoal(
```
Comment (timonegk) [inline bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_engine.h]: This should either return an optional or throw an exception. If we want to do it with exception, please change the return type.

File: bitbots_dynamic_kick/src/kick_node.cpp [hunk 2]
```diff
@@ -142,9 +152,13 @@ std::optional<std::pair<geometry_msgs::Pose, geometry_msgs::Pose>> KickNode::get
...
-  tf_buffer_.transform(r_foot_origin, r_foot_transformed, "l_sole",
-                       ros::Duration(0.2)); // TODO lookup thrown exceptions in internet and catch
-  tf_buffer_.transform(l_foot_origin, l_foot_transformed, "r_sole", ros::Duration(0.2));
+  try {
+    tf_buffer_.transform(r_foot_origin, r_foot_transformed, "l_sole",
+                         ros::Duration(0.2)); // TODO lookup thrown exceptions in internet and catch
+    tf_buffer_.transform(l_foot_origin, l_foot_transformed, "r_sole", ros::Duration(0.2));
+  } catch (tf2::TransformException &e) {
+    return std::nullopt;
+  }
```
Comment (timonegk) [inline bitbots_dynamic_kick/src/kick_node.cpp]: Maybe this should `throw` too instead of using optional?

**Comment by ftsell** [comment]
@timonegk 
I agree that we should keep the style consistent and either throw an exception or use optional.

I vote for throwing an exception because we can pass extra error data that way too.

I'll work on it wednesday
